# -*- coding: utf-8 -*-
"""Brazil Trading.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oEsHjCvz5XE3rIzBj0eHPUo8g76Fktlb

# Brazil Trading Data
"""

import pandas as pd

df_exports = pd.read_csv('EXP_2025.csv', sep=';')

df_exports.head()

df_imports = pd.read_csv('IMP_2025.csv', sep=';', engine='python')

df_imports.head()

"""Importação de datasets de tabelas dimensão para complementar as informações"""

df_pais = pd.read_csv('PAIS.csv', sep=';', encoding='latin1')
df_pais.head()

df_uf = pd.read_csv('UF.csv', sep=';', encoding='latin1')
df_uf.head()

df_ncm = pd.read_csv('NCM.csv', sep=';', encoding='latin1')
df_ncm.head()

df_ncmsh = pd.read_csv('NCM_SH.csv', sep=';', encoding='latin1')
df_ncmsh.head()

"""- Juntar import e export e formar um dataset final total de importações e exportações agrupados de estado (UF) por exportado/importado e por NCM (CO_NCM).
- dataset final com junção aplicada deve conter: CO_NCM, SG_UF_NCM, COD_PAIS, VL_FOB_EXPO e VL_FOB_IMPO




O que será necessário para o desenvolvimento das visualizações:
- UF
- País -> em português e em inglês
- KG líquido
- Total FOB
- Produto (SH) -> em português e em inglês
- Produto (NCM) -> em português e em inglês
"""

df_exports_agg = df_exports.groupby(['CO_NCM', 'SG_UF_NCM', 'CO_PAIS'])['VL_FOB'].sum().reset_index()
df_exports_agg = df_exports_agg.rename(columns={'VL_FOB': 'VL_FOB_EXPO', 'CO_PAIS': 'COD_PAIS'})
df_exports_agg.head()

df_imports_agg = df_imports.groupby(['CO_NCM', 'SG_UF_NCM', 'CO_PAIS'])['VL_FOB'].sum().reset_index()
df_imports_agg = df_imports_agg.rename(columns={'VL_FOB': 'VL_FOB_IMPO', 'CO_PAIS': 'COD_PAIS'})
df_imports_agg.head()

df_merged = pd.merge(df_exports_agg, df_imports_agg, on=['CO_NCM', 'SG_UF_NCM', 'COD_PAIS'], how='outer')
df_merged['VL_FOB_EXPO'] = df_merged['VL_FOB_EXPO'].fillna(0)
df_merged['VL_FOB_IMPO'] = df_merged['VL_FOB_IMPO'].fillna(0)
df_merged.head()

df_merged.to_csv('f_trading.csv', sep=';', index=False)

"""### Tabela País:
- CO_PAIS
- NO_PAIS
- NO_PAIS_ING
"""

df_pais = df_pais[['CO_PAIS', 'NO_PAIS', 'NO_PAIS_ING']]
df_pais.head()

df_pais.loc[df_pais['NO_PAIS'] == 'Países Baixos (Holanda)', 'NO_PAIS'] = 'Holanda'
df_pais.loc[df_pais['NO_PAIS'] == 'Holanda', 'NO_PAIS_ING'] = 'Netherlands'

filtered_rows_loc = df_pais.loc[df_pais['NO_PAIS'] == 'Holanda']
print(filtered_rows_loc)

df_pais.to_csv('d_country.csv', sep=';', encoding='utf-8-sig', index=False)

"""###Tabela UF:
- SG_UF
-NO_UF
- NO_REGIAO
"""

df_uf = df_uf[['SG_UF', 'NO_UF', 'NO_REGIAO']]
df_uf.head()

df_uf.to_csv('d_state.csv', sep=';', encoding='utf-8-sig', index=False)

"""###Tabela NCM:
- CO_NCM
- CO_SH6
- NO_NCM_POR
- NO_NCM_ING
"""

df_ncm = df_ncm[['CO_NCM', 'CO_SH6', 'NO_NCM_POR', 'NO_NCM_ING']]
df_ncm.head()

df_ncm.describe()

print(df_ncm['CO_NCM'].nunique())

import csv

df_ncm.to_csv('d_ncm.csv', sep=';', encoding='utf-8-sig', index=False, quoting=csv.QUOTE_ALL)

"""### Tabela SH:
- CO_SH6
- NO_SH6_POR
- NO_SH6_ING
- CO_SH4
- NO_SH4_POR
- NO_SH4_ING
- CO_SH2
- NO_SH2_POR
- NO_SH2_ING
"""

df_sh = df_ncmsh[['CO_SH6', 'NO_SH6_POR', 'NO_SH6_ING', 'CO_SH4', 'NO_SH4_POR', 'NO_SH4_ING', 'CO_SH2', 'NO_SH2_POR', 'NO_SH2_ING']]
df_sh.head()

df_sh.to_csv('d_sh.csv', sep=';', encoding='utf-8-sig', index=False, quoting=csv.QUOTE_ALL)